# Nombre: {firstName}
# Apellido: {lastName}
# Telefono: {phone}
# Nro Factura: {invoiceNumber}
# Fecha de vencimiento de la Factura: {duedate}
# Monto adeudado: {duetotal}

invoice_unpaid = "Hola *{firstName}* 👋 te informo que se ha emitido una nueva factura *#{invoiceNumber}*.\n\nPara evitar la suspensión del servicio, iniciá sesión en https://clientes.4evergaming.com.ar y realizá un pago de *${duetotal} {currency}* antes del *{duedate}*, o también podés realizar una transferencia:\n- - - - - - - - - - - - - - - -\nTITULAR: STEFANO FABI\nCVU: 0000003100090739102124\nAlias: 4evergaming\n- - - - - - - - - - - - - - - -\n\nSi realizas un pago manual por favor enviar el comprobante de la transferencia 🙏\n\nGracias" 
invoice_paid = "Hola *{firstName}* 👋 te informo que la factura *#{invoiceNumber}* ha sido PAGADA ✅🙌 , \nSi necesita asistencia técnica 👨‍💻, por favor contactános 😊\n\nUn abrazo!" 
invoice_duedate = "Hola, *{firstName}* 👋 te informo que la factura: *#{invoiceNumber}* se encuentra dentro del período de gracia 😥.\n\nPara evitar suspensiones en el servicio, por favor iniciá sesión en https://clientes.4evergaming.com.ar y realizá un pago de *{duetotal} {currency}* antes del *{duedate}*, o también podés realizar una transferencia:\n\n- - - - - - - - - - - - - - - -\nTITULAR: STEFANO FABI\nCVU: 0000003100090739102124\nAlias: 4evergaming\n- - - - - - - - - - - - - - - -\n\nEn caso de realizar un pago manual por favor enviar el comprobante de la transferencia 🙏\n\nGracias" 
invoice_comingTerminate = "Hola *{firstName}* 👋 te informo que la factura *#{invoiceNumber}* todavía se encuentra en estado NO PAGADA ⚠️⚠️.\n\nPara evitar la cancelación del servicio, por favor iniciá sesión en https://clientes.4evergaming.com.ar y realizá un pago de *{duetotal} {currency}* antes de *hoy* ☢️, o también podés realizar una transferencia:\n- - - - - - - - - - - - - - - -\nTITULAR: STEFANO FABI\nCVU: 0000003100090739102124\nAlias: 4evergaming\n- - - - - - - - - - - - - - - -\n\nSi realizas un pago manual por favor enviar el comprobante de la transferencia 🙏\n\nGracias" 
invoice_auto_debit = "Hola *{firstName}* 👋 te informo que dentro de las próximas horas ⌛ intentaremos realizar el débito correspondiente de tu factura *#{invoiceNumber}* desde tu cuenta 🏦 💳. Le solicitamos que por favor mantenga un saldo de *${duetotal} {currency}* para evitar inconvenientes 🙏\n\nMuchas gracias! 😊" 
order_pending = "Hola *{firstName}* 👋 He notado que generaste un pedido en nuestra tienda y no has realizado el pago correspondiente. ¿Hubo algún problema en el proceso de pago que no te permitió finalizarlo? 🤔 Por favor, hacemelo saber para poder ayudarte en lo que necesites y así poder ofrecerte el servicio que necesitas. Estoy a tu disposición para cualquier consulta o duda que tengas. ¡Saludos!"
client_area_login = "Hola *{firstName}* 👋 Registramos un nuevo inicio de sesión en el área de clientes 🚨🚨\n\n*Fecha: {lastlogin}*\n*IP: {ip}*\n\nSi no fuiste vos comunicate inmediatamente con nosotros! tu cuenta puede estar en peligro 😵"